# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_date_of_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(default='cse', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='year_of_placement',
            field=models.IntegerField(blank=True, default=2016),
        ),
    ]
